// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vegccazncpyfautqjjma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ2NjYXpuY3B5ZmF1dHFqam1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDgwNzUsImV4cCI6MjA2MzMyNDA3NX0.JiLRxbD9qxx2WGmNRvgqxe7sg0ltWSbXgPgKQAZfAbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);